import { useEffect } from "react";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import {
  getProductsAsync,
  setInitialCart,
} from "../src/features/productsSlice";
import Header from "../src/sections/Header";
import SubHeader from "../src/sections/SubHeader";
import SideBar from "../src/sections/SideBar";
import Modal from "../src/components/Modal";
import ProductList from "../src/sections/ProductList";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const isProductsLoading = useSelector(
    (state) => state.products.isProductsLoading
  );
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getProductsAsync());
    if (window.localStorage.getItem("cartProducts")) {
      dispatch(
        setInitialCart(JSON.parse(window.localStorage.getItem("cartProducts")))
      );
    }
  }, [dispatch]);
  return (
    <div className={styles.homeWrapper}>
      <Head>
        <title>Hepsiburada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SubHeader />
      {isProductsLoading ? (
        <div className={styles.loadingWrapper}>
          <span />
        </div>
      ) : (
        <div className={styles.pageWrapper}>
          <SideBar />
          <ProductList />
        </div>
      )}

      <Modal />
    </div>
  );
}
