import Head from "next/head";
import Header from "../src/sections/Header/Header";
import style from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={style.homeWrapper}>
      <Head>
        <title>Hepsiburada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  );
}
